### ISSUE TITLE
Support Resetting Mock For Specific Function Parameters

### ISSUE THREAD

**Issue by mrrosoff** [timkindberg/jest-when#108]
I have a mock, and I have setup a call.

```typescript
const mock = jest.fn();
when(mock).calledWith("hello").mockResolvedValue("world");
```

I then need to implement "Once" style calls, overriding the function.

```typescript
mock.mockReset();
when(mock).calledWith("hello").mockResolvedValueOnce("world");
when(mock).calledWith("hello").mockResolvedValueOnce("example");
```

Unfortunately, this clears all existing when mocks. Ideally, I could do this, which would clear any mocks for this specific set of arguments.

```typescript
when(mock).calledWith("hello").mockReset()
```

It could then be chained something like this:

```typescript
when(mock).calledWith("hello").mockResolvedValue("world");
when(mock)
    .calledWith("hello")
    .mockReset()
    .mockResolvedValueOnce("example");
```

**Comment by timkindberg** [comment]
[v3.7.0](https://github.com/timkindberg/jest-when/releases/tag/v3.7.0)
