### ISSUE TITLE
How might we utilize snapshots for arguments matching?

### ISSUE THREAD

**Issue by Whoaa512** [timkindberg/jest-when#17]
I have a use case where I'm generating a relatively large payload and I'd like when to make a snapshot for one of the arguments.

### Example code

```js
import { when } from 'jest-when'

const fn = jest.fn()

test('match snap', () => {
    expect.hasAssertions()

    when(fn)
        .expectCalledWith(expect.toMatchSnapshot())
        .mockReturnValueOnce('hi')

    expect(fn({ bar: { a: 12 } })).toEqual('hi')
})

```

Basically I want to jest-when to look at the arg and if I pass the asymmetric snapshot matcher to use `expect(arg).toMatchSnapshot()` instead of the normal `.toEqual`

What do you think?

For context, `expect.toMatchSnapshot()` is only available in jest 23+, and even then `expect.toMatchSnapshot()` doesn't actually work like you'd expect.

**Comment by timkindberg** [comment]
I don't think you can use `toMatchSnapshot` in that fashion... it has to be used as an assertion only. I think you'd have to import the payload then assert it equals the snapshot then pass it to `expectCalledWith`.
