### ISSUE TITLE
Allow usage without `calledWith` or `expectCalledWith`

### ISSUE THREAD

**Issue by wh1t3cAt1k** [timkindberg/jest-when#24]
When setting up mocks without any argument expectations, I get the following message: 

`Unintended use: Only use default value in combination with .calledWith(..), or use standard mocking without jest-when.`

However, I would really rather have a single syntax for mock setups across the whole solution.

I understand that it does not play well linguistically with `when`, but perhaps a more neutral alias can be exposed, like `setupMock`, which would not produce this warning.

In fact, I am trying to migrate from a homemade solution where the function is named just that: `setupMock`.

**Comment by timkindberg** [comment]
I'm fine with this, if you'd like to submit a PR. Otherwise not sure if/when I'd get around to it.

**Comment by timkindberg** [comment]
This should now be fixed in v3.4.0
