### ISSUE TITLE
Partial function signature matching

### ISSUE THREAD

**Issue by fasaas** [timkindberg/jest-when#36]
Could there be a workaround for having a partial argument signature matching? Let me illustrate this.
```    
when(method)
      .calledWith(
         foobar, 
         foo, 
         bar, 
         baz, 
         qux, 
         quux, 
         quuz
      )
      .mockReturnValue('Yaaai!);
```

Instead of having this long `calledWith`, to use the same concept as C# uses when testing with `It.Is` to transform the above code into something like:
```    
when(method)
      .calledWithPartial( {
             foobarArg: foobar,
             quxArg: qux
         }
      )
      .mockReturnValue('Yaaai!);
```
This way, you wouldn't need to worry about matching the exact signature over and over, only the variables that matter to you.
I just put the very first method name that popped into my head, but it can most definitely be improved for sure.

Maybe there's an easier way with jest.Any(constructor) but I'm not sure.

Could this thing be achievable?

**Comment by timkindberg** [comment]
You could do this:
```
const _ = expect.anything()
when(method).calledWith(foobar, _, _, _, _, _, quux, _).mockReturnValue('Yaaai!')
```

How about that?

Because I'm mostly against adding features to this library that are not features of the core jest matchers API.

**Comment by fasaas** [comment]
Yep, that is what I was expecting, thanks for taking the time!
