### ISSUE TITLE
Build errors (node-gyp) stemming from bunyan/dtrace-provider deps

### ISSUE THREAD

**Issue by scottadamsmith** [timkindberg/jest-when#37]
Is anyone else getting node-gyp errors related from the Bunyan dependency? I've read through various issues in the Bunyan and dtrace-provider repositories, but haven't found a concrete way around this that doesn't involve:

A) Installing python
B) Installing the windows essentials package
C) Manually editing the package-lock

Mainly just curious if anyone else is seeing this and if they have found a good workaround or if there is something we could change in the package.json to resolve the issue for everyone.

**Comment by timkindberg** [comment]
I've not seen these errors. This seems related: https://github.com/trentm/node-bunyan/issues/570

What version of node/npm are you on?

**Comment by scottadamsmith** [comment]
Yeah, it definitely appears to be stemming from that library. I am on Node 10.14.2 and NPM 6.5.0

**Comment by scottadamsmith** [comment]
I ended up just having to find another way to make my assertion as I wasn't able to figure out how to resolve this. I'm sure I'll give it another shot in the future as I really want to have this at my disposal when testing. Perhaps the dependency will have fixed the issue by then. Feel free to close if you want unless you are still looking into it.

**Comment by timkindberg** [comment]
Sorry you had trouble with it.

**Comment by AndrewSouthpaw** [comment]
I still see build errors like these, and the root cause seems to be `bunyan`:

```
$ npm i -D jest-when

> dtrace-provider@0.8.8 install /Users/.../node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
-----------------------------------------------------------------
Building dtrace-provider failed with exit code 1, falling back
on stub implementation.

Re-run install with V set in your environment to see the build
output, or NODE_DTRACE_PROVIDER_REQUIRE=hard to force an
installation failure.
-----------------------------------------------------------------
  TOUCH Release/obj.target/ndtp.stamp
+ jest-when@3.3.1
added 31 packages from 70 contributors and audited 1616 packages in 13.351s
```

I'm going to take a stab at removing the bunyan dependency, it doesn't seem like the logging functionality used for the library is all that advanced and it'd be nice to trim this dependency that seems to cause build issues frequently.
