### ISSUE TITLE
using symbols in matchers causes an error

### ISSUE THREAD

**Issue by regevbr** [timkindberg/jest-when#40]
```
when(mock).calledWith(Symbol.for(`dummy`));
```
results in "Cannot convert a Symbol value to a string" error at runtime.
The reason is that you try to log debug the matcher using string literals but Symbols can not work in them.
The issue occurs here - 
https://github.com/timkindberg/jest-when/blob/d89f0872a44d3bde4282bf3177d1e1f028cfb1a7/src/when.js#L19

**Comment by timkindberg** [comment]
Ah ok, seems like an easy fix if you'd like to make a PR, I'd release it. Or if you at least figure out what the code change is I can make it and release it.
