### ISSUE TITLE
support given syntax in addition to when

### ISSUE THREAD

**Issue by jeyj0** [timkindberg/jest-when#43]
I like to follow the test pattern of `given`, `when`, `then`. This pattern makes using a syntax using `when` unintuitive in the `given` block (which is where this library would be used).

I have created aliases for the supported functionality in a fork, which look like this:
```javascript
given(..).calledWith(..).returns             === when(..).calledWith(..).mockReturnValue
given(..).calledWith(..).onceReturns         === when(..).calledWith(..).mockReturnValueOnce
given(..).calledWith(..).resolvesTo          === when(..).calledWith(..).mockResolvedValue
given(..).calledWith(..).onceResolvesTo      === when(..).calledWith(..).mockResolvedValueOnce
given(..).calledWith(..).rejectsWith         === when(..).calledWith(..).mockRejectedValue
given(..).calledWith(..).onceRejectsWith     === when(..).calledWith(..).mockRejectedValueOnce
given(..).calledWith(..).isImplementedAs     === when(..).calledWith(..).mockImplementation
given(..).calledWith(..).onceIsImplementedAs === when(..).calledWith(..).mockImplementationOnce
```

This works with `expectCalledWith` too, of course.

The exports `WhenMock`, `verifyAllWhenMocksCalled` and `resetAllWhenMocks` are aliased to `GivenMock`, `verifyAllGivenMocksCalled` and `resetAllGivenMocks` respectively.

It would also "fix" the linguistic problems #24 mentions by allowing `given(..).returns(..)`.

In my implementation the two syntaxes can be combined in any way, which allows for calls like `given(..).calledWith(..).mockReturnValue(..)`. However, it should be relatively simply to disallow this, and I'd be happy to do so.

Is this something you'd be interested in supporting?

**Comment by jeyj0** [comment]
[This](https://github.com/jeyj0/jest-when/commit/b075a94b7673d9263025937748bc98a450c4a098) is the commit that implements this.

**Comment by timkindberg** [comment]
Responded to PR
