### ISSUE TITLE
Allow default return value other than undefined

### ISSUE THREAD

**Issue by simonsmith** [timkindberg/jest-when#6]
Could there be a way to define the value that is always returned when no matches are made with `calledWith`. So being able to set something other than `undefined`:

```js
  const mock = jest.fn();
  when(mock)
    .mockReturnValue('default') // always returned
    .calledWith('blah')
    .mockReturnValue('test'); // returned when `'blah'` is passed
```

**Comment by timkindberg** [comment]
I messed with this a bit the other night but didn't finish and I'm pretty busy lately. If you want to submit a PR that would be awesome!

**Comment by jeyj0** [comment]
Great idea, although I don't see many use-cases. Maybe we can come up with some use-cases to see which naming would be best? I can also imagine this:
```JavaScript
const mock = jest.fn();
when(mock)
  .calledWith('blah')
  .mockReturnValue('test')
  .elseMockReturnValue('default');
```
which I find much more readable, as it follows the well-known if-else structure. I don't know how easily this could be implemented, but I could try to find time to make a PR. :slightly_smiling_face:
