### ISSUE TITLE
Feature request: support function overloading

### ISSUE THREAD

**Issue by micalevisk** [timkindberg/jest-when#62]
Hey! 

While using this lib with [TypeORM](https://typeorm.io), I'm facing this limitation for [function overloading](https://www.typescriptlang.org/docs/handbook/functions.html#overloads).

Let's say I want to mock a call for [`repository.findOne`](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/repository/Repository.ts#L351-L364) method which have 3 overloads. I'll get this:

![ts error](https://user-images.githubusercontent.com/13461315/108575810-d3bd1080-72f1-11eb-8059-ee0e68c5f6de.png)

since jest-when only recognize the **last** overload of `.findOne` which is `findOne(conditions?: FindConditions<Entity>, options?: FindOneOptions<Entity>)` and I'm using the **first** one (which is `findOne(id?: string|number|Date|ObjectID, options?: FindOneOptions<Entity>)`) :confused:

Is there any know workaround for this? Meanwhile I'm using `//@ts-expect-error`

Great lib btw!

**Comment by timkindberg** [comment]
Hi @micalevisk Hmm 🤔 I'm not super good at TypeScript and the types are managed over in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest-when. I've actually not been involved with those at all. I think you'd need to log an issue over there. Perhaps one day we can rewrite this lib in TS, but it won't be soon.
