### ISSUE TITLE
Can't use calledWith null using 3.3.0

### ISSUE THREAD

**Issue by eranelbaz** [timkindberg/jest-when#68]
Seems like this usage of `jest-when` is broke on version 3.3.0, and work using 3.2.0

```
const fn = jest.fn();
when(fn).calledWith(null).mockReturnValue('yay!');
expect(fn(null)).toBe('yay!');
```

the test is failing and i get this in the logs
```
TypeError: Cannot read property '_isAllArgsFunctionMatcher' of null
```

versions - 
```
"jest-when": "^3.3.0",
"jest": "26.6.3"
```

Thanks

**Comment by timkindberg** [comment]
https://github.com/timkindberg/jest-when/releases/tag/v3.3.1

**Comment by timkindberg** [comment]
Thanks for the bug report!!
