### ISSUE TITLE
Default wrongArgs implementation for README

### ISSUE THREAD

**Issue by joebowbeer** [timkindberg/jest-when#91]
Thanks for creating this!

I'm familiar with this [technique](https://github.com/bahmutov/not-allowed) in sinon, and I find that verifying arguments at the call site often results in better tests than verifying them after execution.

In trying to replicate the [patterns](https://glebbahmutov.com/blog/lock-down-sinon-stub/) I've used in sinon, it wasn't clear from the README how to write the default failing function that handles the wrong-args case.

I include my implementation below in hopes that you include it or something similar in your README:

```typescript
// A default implementation that fails
const wrongArgs = (...args: any[]) => {
  throw new Error(`Wrong args: ${JSON.stringify(args, null, 2)}`);
};

when(fn)
  .mockImplementation(wrongArgs)
  .calledWith(correctArgs)
  .mockReturnValue(expectedValue);
```

**Comment by timkindberg** [comment]
Thanks for the idea! That's pretty cool.

I'm starting to hate the README actually, it's getting very busy and hard to find things.

Also I'm starting to think the default behavior needs to be a more explicit abstraction, like maybe rename it`when(fn).defaultImplementation()` vs what it is today.

**Comment by joebowbeer** [comment]
by the way, I've replaced `JSON.stringify` with [util.inspect](https://nodejs.org/api/util.html#utilinspectobject-options) in my current implementation of this function

```typescript
// A default implementation that fails the test
export function wrongArgs(...args: any[]) {
  throw new Error(`Wrong args: ${inspect(args)}`)
}
```
